SET DEFINE OFF;
DROP TABLE TRANSACTIONS CASCADE CONSTRAINTS;

CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ENTITY_NAME      VARCHAR2(50), -- Name of the operated table
    OPERATION_TYPE   VARCHAR2(10), -- operation type (INSERT, UPDATE, DELETE)
    REFERENCE_ID     NUMBER,       -- ID in the referenced table
    OPERATION_DATE   TIMESTAMP DEFAULT SYSTIMESTAMP -- operation date
);

DROP TABLE USERS CASCADE CONSTRAINTS;

CREATE TABLE USERS
(
  USER_ID          INTEGER                      NOT NULL,
  USERNAME         VARCHAR2(50 CHAR)            NOT NULL,
  EMAIL            VARCHAR2(50 CHAR)            NOT NULL,
  PASSWORD_HASH    VARCHAR2(255 CHAR)           NOT NULL,
  PROFILE_PICTURE  VARCHAR2(255 CHAR)           NOT NULL,
  CREATED_AT       TIMESTAMP(0),
  IS_ADMIN         INTEGER                      NOT NULL
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


CREATE UNIQUE INDEX USERS_PK ON USERS
(USER_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE USERS ADD (
  CONSTRAINT USERS_PK
  PRIMARY KEY
  (USER_ID)
  USING INDEX USERS_PK
  ENABLE VALIDATE);



DROP TABLE CHANNELS CASCADE CONSTRAINTS;

CREATE TABLE CHANNELS
(
  CHANNEL_ID    INTEGER                         NOT NULL,
  CHANNEL_NAME  VARCHAR2(100 CHAR)              NOT NULL,
  DESCRIPTION   CLOB
)
LOB (DESCRIPTION) STORE AS SECUREFILE (
  TABLESPACE  USERS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


CREATE UNIQUE INDEX CHANNELS_PK ON CHANNELS
(CHANNEL_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE CHANNELS ADD (
  CONSTRAINT CHANNELS_PK
  PRIMARY KEY
  (CHANNEL_ID)
  USING INDEX CHANNELS_PK
  ENABLE VALIDATE);




DROP TABLE ENTRIES CASCADE CONSTRAINTS;

CREATE TABLE ENTRIES
(
  ENTRY_ID    INTEGER                           NOT NULL,
  TITLE       VARCHAR2(50 CHAR)                 NOT NULL,
  CONTENT     CLOB                              NOT NULL,
  USER_ID     INTEGER                           NOT NULL,
  CHANNEL_ID  INTEGER                           NOT NULL,
  CREATED_AT  TIMESTAMP(0),
  UPDATED_AT  TIMESTAMP(0)
)
LOB (CONTENT) STORE AS SECUREFILE (
  TABLESPACE  USERS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


CREATE UNIQUE INDEX ENTRIES_PK ON ENTRIES
(ENTRY_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE ENTRIES ADD (
  CONSTRAINT ENTRIES_PK
  PRIMARY KEY
  (ENTRY_ID)
  USING INDEX ENTRIES_PK
  ENABLE VALIDATE);


ALTER TABLE ENTRIES ADD (
  FOREIGN KEY (CHANNEL_ID)
  REFERENCES CHANNELS (CHANNEL_ID)
  ENABLE VALIDATE
,  FOREIGN KEY (USER_ID)
  REFERENCES USERS (USER_ID)
  ENABLE VALIDATE);



DROP TABLE COMMENTS CASCADE CONSTRAINTS;

CREATE TABLE COMMENTS
(
  COMMENT_ID  INTEGER                           NOT NULL,
  ENTRY_ID    INTEGER                           NOT NULL,
  USER_ID     INTEGER                           NOT NULL,
  CONTENT     CLOB,
  CREATED_AT  TIMESTAMP(0)
)
LOB (CONTENT) STORE AS SECUREFILE (
  TABLESPACE  USERS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


CREATE UNIQUE INDEX COMMENTS_PK ON COMMENTS
(COMMENT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE COMMENTS ADD (
  CONSTRAINT COMMENTS_PK
  PRIMARY KEY
  (COMMENT_ID)
  USING INDEX COMMENTS_PK
  ENABLE VALIDATE);


ALTER TABLE COMMENTS ADD (
  FOREIGN KEY (ENTRY_ID)
  REFERENCES ENTRIES (ENTRY_ID)
  ENABLE VALIDATE
,  FOREIGN KEY (USER_ID)
  REFERENCES USERS (USER_ID)
  ENABLE VALIDATE);


DROP TABLE LIKES CASCADE CONSTRAINTS;

CREATE TABLE LIKES
(
  LIKE_ID     INTEGER,
  ENTRY_ID    INTEGER,
  COMMENT_ID  INTEGER,
  USER_ID     INTEGER,
  CREATED_AT  TIMESTAMP(0)
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


CREATE UNIQUE INDEX LIKES_PK ON LIKES
(LIKE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE LIKES ADD (
  CONSTRAINT LIKES_PK
  PRIMARY KEY
  (LIKE_ID)
  USING INDEX LIKES_PK
  ENABLE VALIDATE);


ALTER TABLE LIKES ADD (
  FOREIGN KEY (ENTRY_ID)
  REFERENCES ENTRIES (ENTRY_ID)
  ENABLE VALIDATE
,  FOREIGN KEY (COMMENT_ID)
  REFERENCES COMMENTS (COMMENT_ID)
  ENABLE VALIDATE
,  FOREIGN KEY (USER_ID)
  REFERENCES USERS (USER_ID)
  ENABLE VALIDATE);


DROP TABLE REPORTS CASCADE CONSTRAINTS;

CREATE TABLE REPORTS
(
  REPORT_ID   INTEGER                           NOT NULL,
  USER_ID     INTEGER                           NOT NULL,
  ENTRY_ID    INTEGER                           NOT NULL,
  COMMENT_ID  INTEGER                           NOT NULL,
  REASON      CLOB,
  CREATED_AT  TIMESTAMP(0),
  STATUS      VARCHAR2(50 CHAR)
)
LOB (REASON) STORE AS SECUREFILE (
  TABLESPACE  USERS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


CREATE UNIQUE INDEX REPORTS_PK ON REPORTS
(REPORT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE REPORTS ADD (
  CONSTRAINT REPORTS_PK
  PRIMARY KEY
  (REPORT_ID)
  USING INDEX REPORTS_PK
  ENABLE VALIDATE);


ALTER TABLE REPORTS ADD (
  FOREIGN KEY (USER_ID)
  REFERENCES USERS (USER_ID)
  ENABLE VALIDATE
,  FOREIGN KEY (ENTRY_ID)
  REFERENCES ENTRIES (ENTRY_ID)
  ENABLE VALIDATE
,  FOREIGN KEY (COMMENT_ID)
  REFERENCES COMMENTS (COMMENT_ID)
  ENABLE VALIDATE);



DROP TABLE SAVED_ENTRIES CASCADE CONSTRAINTS;

CREATE TABLE SAVED_ENTRIES
(
  SAVED_ID  INTEGER                             NOT NULL,
  USER_ID   INTEGER                             NOT NULL,
  ENTRY_ID  INTEGER                             NOT NULL,
  SAVED_AT  TIMESTAMP(0)
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


CREATE UNIQUE INDEX SAVED_ENTRIES_PK ON SAVED_ENTRIES
(SAVED_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE SAVED_ENTRIES ADD (
  CONSTRAINT SAVED_ENTRIES_PK
  PRIMARY KEY
  (SAVED_ID)
  USING INDEX SAVED_ENTRIES_PK
  ENABLE VALIDATE);


ALTER TABLE SAVED_ENTRIES ADD (
  FOREIGN KEY (USER_ID)
  REFERENCES USERS (USER_ID)
  ENABLE VALIDATE
,  FOREIGN KEY (ENTRY_ID)
  REFERENCES ENTRIES (ENTRY_ID)
  ENABLE VALIDATE);





DROP TABLE MESSAGES CASCADE CONSTRAINTS;

CREATE TABLE MESSAGES
(
  MESSAGE_ID   INTEGER                          NOT NULL,
  SENDER_ID    INTEGER                          NOT NULL,
  RECEIVER_ID  INTEGER                          NOT NULL,
  CONTENT      CLOB                             NOT NULL,
  SENT_AT      TIMESTAMP(0),
  IS_READ      INTEGER,
  IS_SENT      INTEGER,
  READED_AT    INTEGER
)
LOB (CONTENT) STORE AS SECUREFILE (
  TABLESPACE  USERS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


CREATE UNIQUE INDEX MESSAGES_PK ON MESSAGES
(MESSAGE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE MESSAGES ADD (
  CONSTRAINT MESSAGES_PK
  PRIMARY KEY
  (MESSAGE_ID)
  USING INDEX MESSAGES_PK
  ENABLE VALIDATE);


ALTER TABLE MESSAGES ADD (
  FOREIGN KEY (SENDER_ID)
  REFERENCES USERS (USER_ID)
  ENABLE VALIDATE
,  FOREIGN KEY (RECEIVER_ID)
  REFERENCES USERS (USER_ID)
  ENABLE VALIDATE);
CREATE OR REPLACE PACKAGE insert_pkg AS
    -- USERS
    PROCEDURE insert_into_users(
        p_user_id IN NUMBER,
        p_username IN VARCHAR2,
        p_email IN VARCHAR2,
        p_password_hash IN VARCHAR2,
        p_profile_picture IN VARCHAR2,
        p_is_admin IN NUMBER
    );

    -- CHANNELS
    PROCEDURE insert_into_channels(
        p_channel_id IN NUMBER,
        p_channel_name IN VARCHAR2,
        p_description IN CLOB
    );

    -- ENTRIES
    PROCEDURE insert_into_entries(
        p_entry_id IN NUMBER,
        p_title IN VARCHAR2,
        p_content IN CLOB,
        p_user_id IN NUMBER,
        p_channel_id IN NUMBER
    );

    -- MESSAGES
    PROCEDURE insert_into_messages(
        p_message_id IN NUMBER,
        p_sender_id IN NUMBER,
        p_receiver_id IN NUMBER,
        p_content IN CLOB,
        p_is_read IN NUMBER
    );

    -- COMMENTS
    PROCEDURE insert_into_comments(
        p_comment_id IN NUMBER,
        p_entry_id IN NUMBER,
        p_user_id IN NUMBER,
        p_content IN CLOB
    );

    -- LIKES
    PROCEDURE insert_into_likes(
        p_like_id IN NUMBER,
        p_entry_id IN NUMBER,
        p_comment_id IN NUMBER,
        p_user_id IN NUMBER
    );

    -- REPORTS
    PROCEDURE insert_into_reports(
        p_report_id IN NUMBER,
        p_user_id IN NUMBER,
        p_entry_id IN NUMBER,
        p_comment_id IN NUMBER,
        p_reason IN CLOB,
        p_status IN VARCHAR2
    );

    -- SAVED_ENTRIES
    PROCEDURE insert_into_saved_entries(
        p_saved_id IN NUMBER,
        p_user_id IN NUMBER,
        p_entry_id IN NUMBER
    );
END insert_pkg;
/

CREATE OR REPLACE PACKAGE update_pkg AS
    PROCEDURE update_users(
        p_user_id IN NUMBER,
        p_username IN VARCHAR2,
        p_email IN VARCHAR2,
        p_password_hash IN VARCHAR2,
        p_profile_picture IN VARCHAR2,
        p_is_admin IN NUMBER
    );

    PROCEDURE update_channels(
        p_channel_id IN NUMBER,
        p_channel_name IN VARCHAR2,
        p_description IN CLOB
    );

    PROCEDURE update_entries(
        p_entry_id IN NUMBER,
        p_title IN VARCHAR2,
        p_content IN CLOB
    );

    PROCEDURE update_likes(
    p_like_id IN NUMBER,
    p_entry_id IN NUMBER,
    p_comment_id IN NUMBER,
    p_user_id IN NUMBER
    );


    PROCEDURE update_messages(
        p_message_id IN NUMBER,
        p_content IN CLOB,
        p_is_read IN NUMBER
    );

    PROCEDURE update_comments(
        p_comment_id IN NUMBER,
        p_content IN CLOB
    );

    PROCEDURE update_reports(
        p_report_id IN NUMBER,
        p_status IN VARCHAR2
    );

    PROCEDURE update_saved_entries(
        p_saved_id IN NUMBER,
        p_entry_id IN NUMBER
    );
END update_pkg;
/

CREATE OR REPLACE PACKAGE delete_pkg AS
    PROCEDURE delete_from_users(p_user_id IN NUMBER);

    PROCEDURE delete_from_channels(p_channel_id IN NUMBER);

    PROCEDURE delete_from_entries(p_entry_id IN NUMBER);

    PROCEDURE delete_from_messages(p_message_id IN NUMBER);

    PROCEDURE delete_from_comments(p_comment_id IN NUMBER);

    PROCEDURE delete_from_reports(p_report_id IN NUMBER);

    PROCEDURE delete_from_saved_entries(p_saved_id IN NUMBER);

    PROCEDURE delete_from_likes(p_like_id IN NUMBER);

END delete_pkg;
/

CREATE OR REPLACE PACKAGE delete_duplicates_pkg AS
    -- Procedure Definitions
    PROCEDURE delete_duplicates_from_users;
    PROCEDURE delete_duplicates_from_entries;
    PROCEDURE delete_duplicates_from_channels;
    PROCEDURE delete_duplicates_from_messages;
    PROCEDURE delete_duplicates_from_comments;
    PROCEDURE delete_duplicates_from_reports;
    PROCEDURE delete_duplicates_from_saved_entries;
    PROCEDURE delete_duplicates_from_likes;
END delete_duplicates_pkg;
/
CREATE OR REPLACE PACKAGE BODY insert_pkg AS

    -- USERS
    PROCEDURE insert_into_users(
        p_user_id IN NUMBER,
        p_username IN VARCHAR2,
        p_email IN VARCHAR2,
        p_password_hash IN VARCHAR2,
        p_profile_picture IN VARCHAR2,
        p_is_admin IN NUMBER
    ) IS
    BEGIN
        INSERT INTO USERS (
            USER_ID, USERNAME, EMAIL, PASSWORD_HASH, PROFILE_PICTURE, CREATED_AT, IS_ADMIN
        ) VALUES (
            p_user_id,
            p_username,
            p_email,
            p_password_hash,
            p_profile_picture,
            SYSTIMESTAMP,
            p_is_admin
        );
        DBMS_OUTPUT.PUT_LINE('User inserted successfully: ' || p_username);
    END insert_into_users;

    -- CHANNELS
    PROCEDURE insert_into_channels(
        p_channel_id IN NUMBER,
        p_channel_name IN VARCHAR2,
        p_description IN CLOB
    ) IS
    BEGIN
        INSERT INTO CHANNELS (
            CHANNEL_ID, CHANNEL_NAME, DESCRIPTION
        ) VALUES (
            p_channel_id,
            p_channel_name,
            p_description
        );
        DBMS_OUTPUT.PUT_LINE('Channel inserted successfully: ' || p_channel_name);
    END insert_into_channels;

    -- ENTRIES
    PROCEDURE insert_into_entries(
        p_entry_id IN NUMBER,
        p_title IN VARCHAR2,
        p_content IN CLOB,
        p_user_id IN NUMBER,
        p_channel_id IN NUMBER
    ) IS
    BEGIN
        INSERT INTO ENTRIES (
            ENTRY_ID, TITLE, CONTENT, USER_ID, CHANNEL_ID, CREATED_AT, UPDATED_AT
        ) VALUES (
            p_entry_id,
            p_title,
            p_content,
            p_user_id,
            p_channel_id,
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );
        DBMS_OUTPUT.PUT_LINE('Entry inserted successfully: ' || p_title);
    END insert_into_entries;

    -- MESSAGES
    PROCEDURE insert_into_messages(
        p_message_id IN NUMBER,
        p_sender_id IN NUMBER,
        p_receiver_id IN NUMBER,
        p_content IN CLOB,
        p_is_read IN NUMBER
    ) IS
    BEGIN
        INSERT INTO MESSAGES (
            MESSAGE_ID, SENDER_ID, RECEIVER_ID, CONTENT, SENT_AT, IS_READ
        ) VALUES (
            p_message_id,
            p_sender_id,
            p_receiver_id,
            p_content,
            SYSTIMESTAMP,
            p_is_read
        );
        DBMS_OUTPUT.PUT_LINE('Message inserted successfully: ' || p_message_id);
    END insert_into_messages;

    -- COMMENTS
    PROCEDURE insert_into_comments(
        p_comment_id IN NUMBER,
        p_entry_id IN NUMBER,
        p_user_id IN NUMBER,
        p_content IN CLOB
    ) IS
    BEGIN
        INSERT INTO COMMENTS (
            COMMENT_ID, ENTRY_ID, USER_ID, CONTENT, CREATED_AT
        ) VALUES (
            p_comment_id,
            p_entry_id,
            p_user_id,
            p_content,
            SYSTIMESTAMP
        );
        DBMS_OUTPUT.PUT_LINE('Comment inserted successfully: ' || p_comment_id);
    END insert_into_comments;

    -- LIKES
    PROCEDURE insert_into_likes(
        p_like_id IN NUMBER,
        p_entry_id IN NUMBER,
        p_comment_id IN NUMBER,
        p_user_id IN NUMBER
    ) IS
    BEGIN
        INSERT INTO LIKES (
            LIKE_ID, ENTRY_ID, COMMENT_ID, USER_ID, CREATED_AT
        ) VALUES (
            p_like_id,
            p_entry_id,
            p_comment_id,
            p_user_id,
            SYSTIMESTAMP
        );
        DBMS_OUTPUT.PUT_LINE('Like inserted successfully: ' || p_like_id);
    END insert_into_likes;

    -- REPORTS
    PROCEDURE insert_into_reports(
        p_report_id IN NUMBER,
        p_user_id IN NUMBER,
        p_entry_id IN NUMBER,
        p_comment_id IN NUMBER,
        p_reason IN CLOB,
        p_status IN VARCHAR2
    ) IS
    BEGIN
        INSERT INTO REPORTS (
            REPORT_ID, USER_ID, ENTRY_ID, COMMENT_ID, REASON, CREATED_AT, STATUS
        ) VALUES (
            p_report_id,
            p_user_id,
            p_entry_id,
            p_comment_id,
            p_reason,
            SYSTIMESTAMP,
            p_status
        );
        DBMS_OUTPUT.PUT_LINE('Report inserted successfully: ' || p_report_id);
    END insert_into_reports;

    -- SAVED_ENTRIES
    PROCEDURE insert_into_saved_entries(
        p_saved_id IN NUMBER,
        p_user_id IN NUMBER,
        p_entry_id IN NUMBER
    ) IS
    BEGIN
        INSERT INTO SAVED_ENTRIES (
            SAVED_ID, USER_ID, ENTRY_ID, SAVED_AT
        ) VALUES (
            p_saved_id,
            p_user_id,
            p_entry_id,
            SYSTIMESTAMP
        );
        DBMS_OUTPUT.PUT_LINE('Saved Entry inserted successfully: ' || p_saved_id);
    END insert_into_saved_entries;

END insert_pkg;
/

CREATE OR REPLACE PACKAGE BODY update_pkg AS

    -- USERS Table
    PROCEDURE update_users(
        p_user_id IN NUMBER,
        p_username IN VARCHAR2,
        p_email IN VARCHAR2,
        p_password_hash IN VARCHAR2,
        p_profile_picture IN VARCHAR2,
        p_is_admin IN NUMBER
    ) IS
    BEGIN
        UPDATE USERS
        SET USERNAME = p_username,
            EMAIL = p_email,
            PASSWORD_HASH = p_password_hash,
            PROFILE_PICTURE = p_profile_picture,
            IS_ADMIN = p_is_admin
        WHERE USER_ID = p_user_id;

        DBMS_OUTPUT.PUT_LINE('User updated successfully: ' || p_user_id);
    END update_users;

    -- CHANNELS Table
    PROCEDURE update_channels(
        p_channel_id IN NUMBER,
        p_channel_name IN VARCHAR2,
        p_description IN CLOB
    ) IS
    BEGIN
        UPDATE CHANNELS
        SET CHANNEL_NAME = p_channel_name,
            DESCRIPTION = p_description
        WHERE CHANNEL_ID = p_channel_id;

        DBMS_OUTPUT.PUT_LINE('Channel updated successfully: ' || p_channel_id);
    END update_channels;

    -- ENTRIES Table
    PROCEDURE update_entries(
        p_entry_id IN NUMBER,
        p_title IN VARCHAR2,
        p_content IN CLOB
    ) IS
    BEGIN
        UPDATE ENTRIES
        SET TITLE = p_title,
            CONTENT = p_content,
            UPDATED_AT = SYSTIMESTAMP
        WHERE ENTRY_ID = p_entry_id;

        DBMS_OUTPUT.PUT_LINE('Entry updated successfully: ' || p_entry_id);
    END update_entries;

    -- likes table
    PROCEDURE update_likes(
        p_like_id IN NUMBER,
        p_entry_id IN NUMBER,
        p_comment_id IN NUMBER,
        p_user_id IN NUMBER
    ) IS
    BEGIN
        UPDATE LIKES
        SET ENTRY_ID = p_entry_id,
            COMMENT_ID = p_comment_id,
            USER_ID = p_user_id,
            CREATED_AT = SYSTIMESTAMP -- Tarihi güncelliyoruz
        WHERE LIKE_ID = p_like_id;

            IF SQL%ROWCOUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('Like updated successfully: ' || p_like_id);
    ELSE
        DBMS_OUTPUT.PUT_LINE('Like not found: ' || p_like_id);
    END IF;
    END update_likes;


    -- MESSAGES Table
    PROCEDURE update_messages(
        p_message_id IN NUMBER,
        p_content IN CLOB,
        p_is_read IN NUMBER
    ) IS
    BEGIN
        UPDATE MESSAGES
        SET CONTENT = p_content,
            IS_READ = p_is_read
        WHERE MESSAGE_ID = p_message_id;

        DBMS_OUTPUT.PUT_LINE('Message updated successfully: ' || p_message_id);
    END update_messages;

    -- COMMENTS Table
    PROCEDURE update_comments(
        p_comment_id IN NUMBER,
        p_content IN CLOB
    ) IS
    BEGIN
        UPDATE COMMENTS
        SET CONTENT = p_content
        WHERE COMMENT_ID = p_comment_id;

        DBMS_OUTPUT.PUT_LINE('Comment updated successfully: ' || p_comment_id);
    END update_comments;

    -- REPORTS Table
    PROCEDURE update_reports(
        p_report_id IN NUMBER,
        p_status IN VARCHAR2
    ) IS
    BEGIN
        UPDATE REPORTS
        SET STATUS = p_status
        WHERE REPORT_ID = p_report_id;

        DBMS_OUTPUT.PUT_LINE('Report updated successfully: ' || p_report_id);
    END update_reports;

    -- SAVED_ENTRIES Table
    PROCEDURE update_saved_entries(
        p_saved_id IN NUMBER,
        p_entry_id IN NUMBER
    ) IS
    BEGIN
        UPDATE SAVED_ENTRIES
        SET ENTRY_ID = p_entry_id
        WHERE SAVED_ID = p_saved_id;

        DBMS_OUTPUT.PUT_LINE('Saved Entry updated successfully: ' || p_saved_id);
    END update_saved_entries;

END update_pkg;
/

CREATE OR REPLACE PACKAGE BODY delete_pkg AS

    -- USERS -
    PROCEDURE delete_from_users(p_user_id IN NUMBER) IS
    BEGIN
        DELETE FROM USERS WHERE USER_ID = p_user_id;
        DBMS_OUTPUT.PUT_LINE('User deleted successfully: ' || p_user_id);
    END delete_from_users;

    -- CHANNELS -
    PROCEDURE delete_from_channels(p_channel_id IN NUMBER) IS
    BEGIN
        DELETE FROM CHANNELS WHERE CHANNEL_ID = p_channel_id;
        DBMS_OUTPUT.PUT_LINE('Channel deleted successfully: ' || p_channel_id);
    END delete_from_channels;

    -- ENTRIES -
    PROCEDURE delete_from_entries(p_entry_id IN NUMBER) IS
    BEGIN
        DELETE FROM ENTRIES WHERE ENTRY_ID = p_entry_id;
        DBMS_OUTPUT.PUT_LINE('Entry deleted successfully: ' || p_entry_id);
    END delete_from_entries;


    --LIKES TABLE
    PROCEDURE delete_from_likes(
    p_like_id IN NUMBER
    ) IS
    BEGIN
    DELETE FROM LIKES
    WHERE LIKE_ID = p_like_id;

    IF SQL%ROWCOUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('Like deleted successfully: ' || p_like_id);
    ELSE
        DBMS_OUTPUT.PUT_LINE('Like not found: ' || p_like_id);
    END IF;
    END delete_from_likes;


    -- MESSAGES -
    PROCEDURE delete_from_messages(p_message_id IN NUMBER) IS
    BEGIN
        DELETE FROM MESSAGES WHERE MESSAGE_ID = p_message_id;
        DBMS_OUTPUT.PUT_LINE('Message deleted successfully: ' || p_message_id);
    END delete_from_messages;

    -- COMMENTS -
    PROCEDURE delete_from_comments(p_comment_id IN NUMBER) IS
    BEGIN
        DELETE FROM COMMENTS WHERE COMMENT_ID = p_comment_id;
        DBMS_OUTPUT.PUT_LINE('Comment deleted successfully: ' || p_comment_id);
    END delete_from_comments;

    -- REPORTS -
    PROCEDURE delete_from_reports(p_report_id IN NUMBER) IS
    BEGIN
        DELETE FROM REPORTS WHERE REPORT_ID = p_report_id;
        DBMS_OUTPUT.PUT_LINE('Report deleted successfully: ' || p_report_id);
    END delete_from_reports;

    -- SAVED_ENTRIES -
    PROCEDURE delete_from_saved_entries(p_saved_id IN NUMBER) IS
    BEGIN
        DELETE FROM SAVED_ENTRIES WHERE SAVED_ID = p_saved_id;
        DBMS_OUTPUT.PUT_LINE('Saved Entry deleted successfully: ' || p_saved_id);
    END delete_from_saved_entries;

END delete_pkg;
/

CREATE OR REPLACE PACKAGE BODY delete_duplicates_pkg AS

    -- Delete USERS Duplicates
    PROCEDURE delete_duplicates_from_users IS
    BEGIN
        DELETE FROM USERS
        WHERE user_id IN (
            SELECT user_id
            FROM (
                SELECT user_id, ROW_NUMBER() OVER (PARTITION BY username, email ORDER BY user_id) AS row_num
                FROM USERS
            )
            WHERE row_num > 1
        );
        DBMS_OUTPUT.PUT_LINE('Duplicate users deleted successfully.');
    END delete_duplicates_from_users;

    PROCEDURE delete_duplicates_from_entries IS
    BEGIN
        DELETE FROM ENTRIES
        WHERE entry_id IN (
            SELECT entry_id
            FROM (
                SELECT entry_id, ROW_NUMBER() OVER (PARTITION BY title, content ORDER BY entry_id) AS row_num
                FROM ENTRIES
            )
            WHERE row_num > 1
        );
        DBMS_OUTPUT.PUT_LINE('Duplicate entries deleted successfully.');
    END delete_duplicates_from_entries;

    PROCEDURE delete_duplicates_from_channels IS
    BEGIN
        DELETE FROM CHANNELS
        WHERE channel_id IN (
            SELECT channel_id
            FROM (
                SELECT channel_id, ROW_NUMBER() OVER (PARTITION BY channel_name ORDER BY channel_id) AS row_num
                FROM CHANNELS
            )
            WHERE row_num > 1
        );
        DBMS_OUTPUT.PUT_LINE('Duplicate channels deleted successfully.');
    END delete_duplicates_from_channels;

    PROCEDURE delete_duplicates_from_messages IS
    BEGIN
        DELETE FROM MESSAGES
        WHERE message_id IN (
            SELECT message_id
            FROM (
                SELECT message_id, ROW_NUMBER() OVER (PARTITION BY sender_id, receiver_id, content ORDER BY message_id) AS row_num
                FROM MESSAGES
            )
            WHERE row_num > 1
        );
        DBMS_OUTPUT.PUT_LINE('Duplicate messages deleted successfully.');
    END delete_duplicates_from_messages;

    PROCEDURE delete_duplicates_from_comments IS
    BEGIN
        DELETE FROM COMMENTS
        WHERE comment_id IN (
            SELECT comment_id
            FROM (
                SELECT comment_id, ROW_NUMBER() OVER (PARTITION BY entry_id, user_id, content ORDER BY comment_id) AS row_num
                FROM COMMENTS
            )
            WHERE row_num > 1
        );
        DBMS_OUTPUT.PUT_LINE('Duplicate comments deleted successfully.');
    END delete_duplicates_from_comments;

    PROCEDURE delete_duplicates_from_reports IS
    BEGIN
        DELETE FROM REPORTS
        WHERE report_id IN (
            SELECT report_id
            FROM (
                SELECT report_id, ROW_NUMBER() OVER (PARTITION BY user_id, entry_id, comment_id ORDER BY report_id) AS row_num
                FROM REPORTS
            )
            WHERE row_num > 1
        );
        DBMS_OUTPUT.PUT_LINE('Duplicate reports deleted successfully.');
    END delete_duplicates_from_reports;

    PROCEDURE delete_duplicates_from_saved_entries IS
    BEGIN
        DELETE FROM SAVED_ENTRIES
        WHERE saved_id IN (
            SELECT saved_id
            FROM (
                SELECT saved_id, ROW_NUMBER() OVER (PARTITION BY user_id, entry_id ORDER BY saved_id) AS row_num
                FROM SAVED_ENTRIES
            )
            WHERE row_num > 1
        );
        DBMS_OUTPUT.PUT_LINE('Duplicate saved entries deleted successfully.');
    END delete_duplicates_from_saved_entries;

    PROCEDURE delete_duplicates_from_likes IS
    BEGIN
        DELETE FROM LIKES
        WHERE like_id IN (
            SELECT like_id
            FROM (
                SELECT like_id, ROW_NUMBER() OVER (PARTITION BY entry_id, comment_id, user_id ORDER BY like_id) AS row_num
                FROM LIKES
            )
            WHERE row_num > 1
        );
        DBMS_OUTPUT.PUT_LINE('Duplicate likes deleted successfully.');
    END delete_duplicates_from_likes;

END delete_duplicates_pkg;
/
CREATE OR REPLACE TRIGGER users_after_insert_trigger
AFTER INSERT ON USERS
FOR EACH ROW
BEGIN
    INSERT INTO TRANSACTIONS (
        ENTITY_NAME,
        OPERATION_TYPE,
        REFERENCE_ID,
        OPERATION_DATE
    ) VALUES (
        'USERS', -- Operated table
        'INSERT', -- operation type
        :NEW.USER_ID,
        SYSTIMESTAMP -- operation date
    );
END;
/



CREATE OR REPLACE TRIGGER entries_after_insert_trigger
AFTER INSERT ON ENTRIES
FOR EACH ROW
BEGIN
    INSERT INTO TRANSACTIONS (
        ENTITY_NAME,
        OPERATION_TYPE,
        REFERENCE_ID,
        OPERATION_DATE
    ) VALUES (
        'ENTRIES', -- Operated table
        'INSERT', -- operation type
        :NEW.ENTRY_ID,
        SYSTIMESTAMP -- operation date
    );
END;
/




CREATE OR REPLACE TRIGGER messages_after_insert_trigger
AFTER INSERT ON MESSAGES
FOR EACH ROW
BEGIN
    INSERT INTO TRANSACTIONS (
        ENTITY_NAME,
        OPERATION_TYPE,
        REFERENCE_ID,
        OPERATION_DATE
    ) VALUES (
        'MESSAGES', -- Operated table
        'INSERT', -- operation type
        :NEW.MESSAGE_ID,
        SYSTIMESTAMP -- operation date
    );
END;
/




CREATE OR REPLACE TRIGGER comments_after_insert_trigger
AFTER INSERT ON COMMENTS
FOR EACH ROW
BEGIN
    INSERT INTO TRANSACTIONS (
        ENTITY_NAME,
        OPERATION_TYPE,
        REFERENCE_ID,
        OPERATION_DATE
    ) VALUES (
        'COMMENTS', -- Operated table
        'INSERT', -- operation type
        :NEW.COMMENT_ID, -- COMMENT_ID of inserted comment
        SYSTIMESTAMP -- Operation time
    );
END;
/




CREATE OR REPLACE TRIGGER likes_after_insert_trigger
AFTER INSERT ON LIKES
FOR EACH ROW
BEGIN
    INSERT INTO TRANSACTIONS (
        ENTITY_NAME,
        OPERATION_TYPE,
        REFERENCE_ID,
        OPERATION_DATE
    ) VALUES (
        'LIKES', -- Operated table
        'INSERT', -- operation type
        :NEW.LIKE_ID,
        SYSTIMESTAMP -- operation date
    );
END;
/



CREATE OR REPLACE TRIGGER reports_after_insert_trigger
AFTER INSERT ON REPORTS
FOR EACH ROW
BEGIN
    INSERT INTO TRANSACTIONS (
        ENTITY_NAME,
        OPERATION_TYPE,
        REFERENCE_ID,
        OPERATION_DATE
    ) VALUES (
        'REPORTS', -- Operated table
        'INSERT', -- operation type
        :NEW.REPORT_ID,
        SYSTIMESTAMP -- operation date
    );
END;
/



CREATE OR REPLACE TRIGGER saved_entries_after_insert_trigger
AFTER INSERT ON SAVED_ENTRIES
FOR EACH ROW
BEGIN
    INSERT INTO TRANSACTIONS (
        ENTITY_NAME,
        OPERATION_TYPE,
        REFERENCE_ID,
        OPERATION_DATE
    ) VALUES (
        'SAVED_ENTRIES', -- Operated table
        'INSERT', -- operation type
        :NEW.SAVED_ID,
        SYSTIMESTAMP -- operation date
    );
END;
/



CREATE OR REPLACE TRIGGER channels_after_insert_trigger
AFTER INSERT ON CHANNELS
FOR EACH ROW
BEGIN
    INSERT INTO TRANSACTIONS (
        ENTITY_NAME,
        OPERATION_TYPE,
        REFERENCE_ID,
        OPERATION_DATE
    ) VALUES (
        'CHANNELS', -- Operated table
        'INSERT', -- operation type
        :NEW.CHANNEL_ID,
        SYSTIMESTAMP -- operation date
    );
END;
/
DECLARE
    v_user_id    NUMBER := 1; -- User ID input
    v_start_date DATE := TO_DATE('2024-01-01', 'YYYY-MM-DD'); -- Start date
    v_end_date   DATE := TO_DATE('2024-12-31', 'YYYY-MM-DD'); -- End date

    -- Temporary variables
    v_entry_title VARCHAR2(4000);
    v_comment_content VARCHAR2(4000);
BEGIN
    -- Query Entries and Comments Together
    FOR entry_comment_rec IN (
        SELECT e.TITLE AS ENTRY_TITLE, c.CONTENT AS COMMENT_CONTENT
        FROM ENTRIES e
        LEFT JOIN COMMENTS c
        ON e.ENTRY_ID = c.ENTRY_ID
        WHERE e.USER_ID = v_user_id
        AND e.CREATED_AT BETWEEN v_start_date AND v_end_date
    ) LOOP
        DBMS_OUTPUT.PUT_LINE('Entry Title: ' || entry_comment_rec.ENTRY_TITLE);
        IF entry_comment_rec.COMMENT_CONTENT IS NOT NULL THEN
            DBMS_OUTPUT.PUT_LINE('   Comment: ' || entry_comment_rec.COMMENT_CONTENT);
        ELSE
            DBMS_OUTPUT.PUT_LINE('   No comments for this entry.');
        END IF;
    END LOOP;
END;
/
